### ISSUE TITLE
Manual Token login error 

### ISSUE THREAD

**Issue by AnisTaluqdar** [beeper/linkedin#19]
Failed to log in: Deserialising to <class 'linkedin_messaging.api_objects.UserProfileResponse'> failed because response was 403. Details: CSRF check failed.

**Comment by sumnerevans** [comment]
You probably entered one of the tokens incorrectly, probably the `JSESSIONID`. Can you give an example of how you invoked the `login-manual` command?

**Comment by AnisTaluqdar** [comment]
Example: login-manual li_at  "JSESSIONID"

**Comment by AnisTaluqdar** [comment]
Ah I was used jsessionid as a string  " "

I have to remove " "

Now it successfully logged

**Comment by sumnerevans** [comment]
I guess I should make the command automatically strip off the `"`s...
