### ISSUE TITLE
Normal login error 

### ISSUE THREAD

**Issue by AnisTaluqdar** [beeper/linkedin#20]
Failed to log in: 'NoneType' object is not subscriptable

**Comment by willydouhard** [comment]
I am experiencing the same issue, any info available?

**Comment by sumnerevans** [comment]
Probably use the new `login-manual` command instead. I should probably remove the `login` command since it seems to just not work anymore.

**Comment by AnisTaluqdar** [comment]
#19 @sumnerevans 

login-manual also have error.

**Comment by willydouhard** [comment]
This code works ok (executed on my machine, not Matrix):

python```import asyncio
import logging
from pathlib import Path

from linkedin_messaging import ChallengeException, LinkedInMessaging

async def main():
    logging.basicConfig()
    logging.getLogger().setLevel(logging.DEBUG)

    linkedin = LinkedInMessaging()
    try:
        await linkedin.login("REDACTED", "REDACTED")
    except ChallengeException:
        await linkedin.enter_2fa(input("2fa code: "))

    conversations = await linkedin.get_conversations()
    for c in conversations.elements:
        print(c)


loop = asyncio.get_event_loop()
loop.run_until_complete(main())```

This is weird because the error comes from https://github.com/beeper/linkedin/blob/master/linkedin_matrix/commands/auth.py#L150 if I am not mistaken. It is doing basically the same thing as the code above.

**Comment by willydouhard** [comment]
Ok I ran the same code but on the matrix server directly (through ssh). I was able to reproduce with a more precise error:
```
File "//f.py", line 13, in main
    await linkedin.login("REDACTED", "REDACTED")
  File "/usr/local/lib/python3.9/dist-packages/linkedin_messaging/linkedin.py", line 194, in login
    self.two_factor_payload = {
  File "/usr/local/lib/python3.9/dist-packages/linkedin_messaging/linkedin.py", line 195, in <dictcomp>
    k: soup.find("input", {"name": k})["value"]
TypeError: 'NoneType' object is not subscriptable
ERROR:asyncio:Unclosed client session
```

**Comment by willydouhard** [comment]
Inspecting `await login_response.text()` it looks like it is getting a captcha challenge. I am not going to provide the whole thing but several mentions of captcha are in the HTML like so:

`<iframe class="hidden" id="captcha-internal" src="" frameborder="0" role="presentation" title="Captcha Challenge"></iframe>`

**Comment by sumnerevans** [comment]
Logging in from a different IP than you normally log in from will almost always cause the captcha
