### ISSUE TITLE
login command does not work and doesn't have a good error message or logging

### ISSUE THREAD

**Issue by sumnerevans** [beeper/linkedin#6]
`login <email>` command always returns the (very unhelpful) error:

```
Failed to log in
```

and doesn't log anything.

**Comment by ctron** [comment]
I have the same issue

**Comment by copoer** [comment]
I found a temporary solution to this problem. It seems like they require you to fill out a CAPTCHA when you login in from a new IP. If you have the ability to proxy through your Synapse server to login then you can first login through your browser when its setup through your synapse server and complete the CAPTCHA/login process. Then login through the bot and it should work.

[An easy way to do this is to SSH tunnel into the synapse machine then use the foxy proxy add on](https://www.willchatham.com/security/simple-ssh-tunneling-with-foxyproxy/)

1. `ssh user@ip -D 8118`
2. Setup foxy proxy add-on to localhost port 8118
3. Login to LinkedIn on your browser and complete Captcha
4. Login to LinkedIn on the bot

**Comment by ctron** [comment]
Awesome, this worked like a charm. Instead of using an additional addon, you can simply configure your browser to use SOCKS as the proxy (`localhost:81181` in your case).

I had to log out of LinkedIn, and log in again. Otherwise I did keep my session and didn't seem to flag the IP as ok.
