### ISSUE TITLE
Feature request: support for InMail messages

### ISSUE THREAD

**Issue by yann-soubeyrand** [beeper/linkedin#67]
Hi,

It would be great if the bridge could support InMail messages.

**Comment by sumnerevans** [comment]
The bridge already does support InMail. If there are specific messages that aren't working, please include bridge logs relevant to the failed message.

**Comment by yann-soubeyrand** [comment]
Hi @sumnerevans, I reached the support because I did see empty chats when someone invites me on LinkedIn (with a message) or sends me an InMail and I got the following answer:

> Ah. That is an inmail. InMail Messages will not show up in Beeper unless another message is sent. - G

And, indeed, I never see the messages which were part of an invites nor I see the first InMail sent to me. That’s why I opened this feature request. Is it expected?

**Comment by sumnerevans** [comment]
That is a Beeper-specific bug which has been fixed and will be deployed soon. This tracker is for issues specific to the LinkedIn bridge and should not be used for Beeper support issues, we have separate tracking for those issues internally at Beeper.
